/**
 * Ручные метаданные проектов: описания, теги, материалы.
 * Ключ — нормализованное имя папки (без хвостовых пробелов).
 */
export const CATEGORY_META = {
  Общепит: { slug: 'food', titleRu: 'Общепит', titleEn: 'Hospitality' },
  Квартиры: { slug: 'apartments', titleRu: 'Квартиры и интерьеры', titleEn: 'Apartments & interiors' },
  Офисы: { slug: 'offices', titleRu: 'Офисы', titleEn: 'Offices' },
  'Торговые центры': { slug: 'malls', titleRu: 'Торговые центры', titleEn: 'Shopping centers' },
  Магазин: { slug: 'retail', titleRu: 'Магазины и ритейл', titleEn: 'Retail' },
  Клубы: { slug: 'clubs', titleRu: 'Клубы', titleEn: 'Clubs' },
  Выставки: { slug: 'exhibitions', titleRu: 'Выставки', titleEn: 'Exhibitions' },
  Музеи: { slug: 'museums', titleRu: 'Музеи', titleEn: 'Museums' },
  Картины: { slug: 'paintings', titleRu: 'Картины', titleEn: 'Paintings' },
}

/** Доп. описания и теги по slug проекта */
export const PROJECT_OVERRIDES = {
  'restoran-vasabi-2017': {
    titleRu: 'Ресторан «Васаби»',
    titleEn: 'Wasabi Restaurant',
    cityRu: 'Екатеринбург',
    cityEn: 'Yekaterinburg',
    year: 2017,
    tags: ['общепит', 'декоративная штукатурка', 'художественная роспись', 'ресторан'],
    descriptionRu:
      'Художник-декоратор: нанесение декоративной штукатурки и художественная роспись интерьера ресторана японской кухни.',
    descriptionEn:
      'Decorative plaster and mural work for a Japanese restaurant interior.',
  },
  'restoran-borsh-2018': {
    titleRu: 'Ресторан «Борщ»',
    titleEn: 'Borscht Restaurant',
    cityRu: 'Екатеринбург',
    cityEn: 'Yekaterinburg',
    year: 2018,
    tags: ['общепит', 'декоративная штукатурка', 'художественная роспись', 'ресторан'],
    descriptionRu:
      'Декоративная штукатурка и художественная роспись в интерьере ресторана «Борщ».',
    descriptionEn: 'Decorative plaster and murals for Borscht restaurant.',
  },
  'restoran-barbara-2020': {
    titleRu: 'Ресторан «Барбара»',
    titleEn: 'Barbara Restaurant',
    cityRu: 'Екатеринбург',
    cityEn: 'Yekaterinburg',
    year: 2020,
    tags: ['общепит', 'декоративная штукатурка', 'художественная роспись', 'ресторан'],
    descriptionRu:
      'Декоративная отделка и роспись интерьера ресторана «Барбара».',
    descriptionEn: 'Decorative finishes and murals for Barbara restaurant.',
  },
  'restoran-brodvei-2020': {
    titleRu: 'Ресторан «Бродвей»',
    titleEn: 'Broadway Restaurant',
    cityRu: 'Екатеринбург',
    cityEn: 'Yekaterinburg',
    year: 2020,
    tags: ['общепит', 'декоративная штукатурка', 'художественная роспись', 'ресторан'],
    descriptionRu:
      'Декоративная штукатурка и художественная роспись в ресторане «Бродвей».',
    descriptionEn: 'Decorative plaster and murals for Broadway restaurant.',
  },
  'restoran-brodskii-2020': {
    titleRu: 'Ресторан «Бродский»',
    titleEn: 'Brodsky Restaurant',
    cityRu: 'Екатеринбург',
    cityEn: 'Yekaterinburg',
    year: 2020,
    tags: ['общепит', 'декоративная штукатурка', 'художественная роспись', 'ресторан'],
    descriptionRu:
      'Декоративная штукатурка и художественная роспись в ресторане «Бродский».',
    descriptionEn: 'Decorative plaster and murals for Brodsky restaurant.',
  },
  'restoran-dorian-grei-2020': {
    titleRu: 'Ресторан «Дориан Грей»',
    titleEn: 'Dorian Gray Restaurant',
    cityRu: 'Екатеринбург',
    cityEn: 'Yekaterinburg',
    year: 2020,
    tags: ['общепит', 'декорирование', 'состаривание кирпича', 'ресторан'],
    descriptionRu: 'Декорирование и состаривание кирпича в интерьере ресторана.',
    descriptionEn: 'Brick aging and decorative finishing for the restaurant.',
  },
  'set-kafe-engels-2020': {
    titleRu: 'Сеть кафе «Engels»',
    titleEn: 'Engels Café Chain',
    cityRu: 'Екатеринбург',
    cityEn: 'Yekaterinburg',
    year: 2020,
    tags: ['общепит', 'декоративная штукатурка', 'художественная роспись', 'кафе'],
    descriptionRu:
      'Декоративная штукатурка и художественная роспись для сети кафе Engels.',
    descriptionEn: 'Decorative plaster and murals for the Engels café chain.',
  },
  'restoran-soika-2023': {
    titleRu: 'Ресторан «Сойка»',
    titleEn: 'Soyka Restaurant',
    cityRu: 'Екатеринбург',
    cityEn: 'Yekaterinburg',
    year: 2023,
    website: 'https://soyka.rest',
    tags: ['общепит', 'декоративная штукатурка', 'художественная роспись', 'санузел', 'входная группа', 'ресторан'],
    descriptionRu:
      'Декоративная штукатурка и художественная роспись: санузел и входная группа ресторана «Сойка».',
    descriptionEn:
      'Decorative plaster and murals for the restroom and entrance of Soyka restaurant.',
  },
  'kafe-lo-vegano-2023': {
    titleRu: 'Кафе «Lo Vegano»',
    titleEn: 'Lo Vegano Café',
    cityRu: 'Екатеринбург',
    cityEn: 'Yekaterinburg',
    year: 2023,
    tags: ['общепит', 'декоративная штукатурка', 'художественная роспись', 'санузел', 'входная группа', 'кафе'],
    descriptionRu:
      'Декоративная штукатурка и роспись: санузел и входная группа кафе Lo Vegano.',
    descriptionEn:
      'Decorative plaster and murals for Lo Vegano café entrance and restroom.',
  },
  'restoran-armyanskii-restoran-2024': {
    titleRu: 'Армянский ресторан',
    titleEn: 'Armenian Restaurant',
    cityRu: 'Каменск-Уральский',
    cityEn: 'Kamensk-Uralsky',
    year: 2024,
    tags: ['общепит', 'венецианская штукатурка', 'ресторан'],
    descriptionRu: 'Венецианская штукатурка в интерьере армянского ресторана.',
    descriptionEn: 'Venetian plaster for an Armenian restaurant interior.',
  },
  'kvartira-ekaterinburg-tsentr-2023': {
    titleRu: 'Квартира — центр',
    titleEn: 'Apartment — City Center',
    cityRu: 'Екатеринбург',
    cityEn: 'Yekaterinburg',
    year: 2023,
    tags: ['квартира', 'декоративная штукатурка', 'перья', 'интерьер'],
    descriptionRu: 'Декоративная штукатурка «Перья» в квартире в центре города.',
    descriptionEn: '“Feathers” decorative plaster in a city-center apartment.',
  },
  'kvartira-uralskii-2024': {
    titleRu: 'Квартира — Уральский',
    titleEn: 'Apartment — Uralsky',
    cityRu: 'Екатеринбург',
    cityEn: 'Yekaterinburg',
    year: 2024,
    tags: ['квартира', 'шёлк', 'тонкослойная штукатурка', 'интерьер'],
    descriptionRu: 'Тонкослойная декоративная штукатурка «Шёлк».',
    descriptionEn: 'Thin-layer “Silk” decorative plaster.',
  },
  'kottedzh-kosuleno-2024': {
    titleRu: 'Коттедж — Косулино',
    titleEn: 'Cottage — Kosulino',
    cityRu: 'Косулино',
    cityEn: 'Kosulino',
    year: 2024,
    tags: ['коттедж', 'декоративная штукатурка', 'имитация скалы', 'вода', 'интерьер'],
    descriptionRu:
      'Имитация объёмной скалы с подачей воды — декоративная штукатурка в коттедже.',
    descriptionEn: 'Sculpted rock imitation with a water feature in a private cottage.',
  },
  'pentkhaus-ekaterinburg-2024': {
    titleRu: 'Пентхаус',
    titleEn: 'Penthouse',
    cityRu: 'Екатеринбург',
    cityEn: 'Yekaterinburg',
    year: 2024,
    tags: ['пентхаус', 'декоративная штукатурка', 'полы', 'микроцемент', 'интерьер'],
    descriptionRu: 'Декоративная штукатурка, полы и микроцемент в пентхаусе.',
    descriptionEn: 'Decorative plaster, floors and microcement in a penthouse.',
  },
  'podezd-zhk-repina-2022': {
    titleRu: 'Подъезд ЖК «Репина»',
    titleEn: 'Repina Residential Entrance',
    cityRu: 'Екатеринбург',
    cityEn: 'Yekaterinburg',
    year: 2022,
    tags: ['подъезд', 'декоративная штукатурка', 'полы', 'микроцемент', 'входная группа'],
    descriptionRu: 'Декоративная штукатурка полов и микроцемент в подъезде ЖК «Репина».',
    descriptionEn: 'Decorative floor plaster and microcement in a residential lobby.',
  },
  'kvartira-ekaterinburg-tsentr-2025': {
    titleRu: 'Квартира — центр',
    titleEn: 'Apartment — City Center',
    cityRu: 'Екатеринбург',
    cityEn: 'Yekaterinburg',
    year: 2025,
    tags: ['квартира', 'декоративная штукатурка', 'санузел', 'интерьер'],
    descriptionRu: 'Декоративная штукатурка в санузле квартиры в центре Екатеринбурга.',
    descriptionEn: 'Decorative plaster in a bathroom of a city-center apartment.',
  },
  'kvartira-ekaterinburg-akadem-gorodok-2025': {
    titleRu: 'Квартира — Академгородок',
    titleEn: 'Apartment — Akademgorodok',
    cityRu: 'Екатеринбург',
    cityEn: 'Yekaterinburg',
    year: 2025,
    tags: ['квартира', 'декоративная штукатурка', 'санузел', 'микроцемент', 'интерьер'],
    descriptionRu: 'Декоративная штукатурка и микроцемент в санузле квартиры в Академгородке.',
    descriptionEn: 'Decorative plaster and microcement in an Akademgorodok apartment bathroom.',
  },
  'kvartira-sochi-2025': {
    titleRu: 'Квартира — Сочи',
    titleEn: 'Apartment — Sochi',
    cityRu: 'Сочи',
    cityEn: 'Sochi',
    year: 2025,
    tags: ['квартира', 'декоративная штукатурка', 'под ключ', 'интерьер'],
    descriptionRu: 'Декоративная штукатурка под ключ в квартире в Сочи.',
    descriptionEn: 'Turnkey decorative plaster for an apartment in Sochi.',
  },
  'kottedzh-alapaevsk-2025': {
    titleRu: 'Коттедж — Алапаевск',
    titleEn: 'Cottage — Alapaevsk',
    cityRu: 'Алапаевск',
    cityEn: 'Alapaevsk',
    year: 2025,
    tags: ['коттедж', 'бассейн', 'венецианская штукатурка', 'травертин', 'микроцемент'],
    descriptionRu:
      'Стены бассейна: венецианская штукатурка, травертин, микроцемент.',
    descriptionEn: 'Pool walls: Venetian plaster, travertine and microcement.',
  },
  'kottedzh-ekaterinburg-akadem-gorodok-2025': {
    titleRu: 'Коттедж — Академгородок',
    titleEn: 'Cottage — Akademgorodok',
    cityRu: 'Екатеринбург',
    cityEn: 'Yekaterinburg',
    year: 2025,
    tags: ['коттедж', 'бассейн', 'венецианская штукатурка', 'травертин', 'микроцемент'],
    descriptionRu:
      'Стены бассейна: венецианская штукатурка, травертин, микроцемент.',
    descriptionEn: 'Pool walls: Venetian plaster, travertine and microcement.',
  },
  'kvartira-ekaterinburg-gagarina-2026': {
    titleRu: 'Квартира — Гагарина',
    titleEn: 'Apartment — Gagarina',
    cityRu: 'Екатеринбург',
    cityEn: 'Yekaterinburg',
    year: 2026,
    tags: ['квартира', 'декоративная штукатурка', 'травертин', 'карта мира', 'интерьер'],
    descriptionRu: 'Декоративная штукатурка и карта мира из травертина.',
    descriptionEn: 'Decorative plaster and a world map made of travertine.',
  },
  'ofis-logisticheskoi-kompanii-transportnye-traditsii-2023': {
    titleRu: 'Офис «Транспортные Традиции»',
    titleEn: 'Transport Traditions Office',
    cityRu: 'Екатеринбург',
    cityEn: 'Yekaterinburg',
    year: 2023,
    tags: ['офис', 'декоративная штукатурка', 'художественная роспись'],
    descriptionRu:
      'Роспись и декоративная штукатурка в офисе логистической компании «Транспортные Традиции».',
    descriptionEn:
      'Murals and decorative plaster for the Transport Traditions logistics office.',
  },
  'torgovyi-tsentr-uspenskii-2020': {
    titleRu: 'ТЦ «Успенский»',
    titleEn: 'Uspensky Shopping Center',
    cityRu: 'Екатеринбург',
    cityEn: 'Yekaterinburg',
    year: 2020,
    tags: ['торговый центр', 'художественная роспись'],
    descriptionRu: 'Художественная роспись в торговом центре «Успенский».',
    descriptionEn: 'Mural work for the Uspensky shopping center.',
  },
  'kluby-virtualnoi-realnosti-center-2017': {
    titleRu: 'Клубы VR «Center»',
    titleEn: 'Center VR Clubs',
    cityRu: 'Екатеринбург',
    cityEn: 'Yekaterinburg',
    year: 2017,
    tags: ['клуб', 'художественная роспись', 'виртуальная реальность'],
    descriptionRu:
      'Художественная роспись клубов виртуальной реальности Center (Ельцин Центр).',
    descriptionEn: 'Murals for Center VR clubs at the Yeltsin Center.',
  },
  'magazin-magazin-russkikh-brendov-mega-2018': {
    titleRu: 'Магазин русских брендов',
    titleEn: 'Russian Brands Store',
    cityRu: 'Екатеринбург',
    cityEn: 'Yekaterinburg',
    year: 2018,
    tags: ['магазин', 'художественная роспись', 'ритейл'],
    descriptionRu: 'Художественная роспись в магазине русских брендов (МЕГА).',
    descriptionEn: 'Murals for a Russian brands store at MEGA mall.',
  },
  'klub-kdts-2022': {
    titleRu: 'Клуб КДЦ',
    titleEn: 'KDC Club',
    cityRu: 'Пермь',
    cityEn: 'Perm',
    year: 2022,
    tags: ['клуб', 'художественная роспись'],
    descriptionRu: 'Художественная роспись в клубе КДЦ.',
    descriptionEn: 'Mural work for the KDC club.',
  },
  'art-perm-2017': {
    titleRu: 'Арт Пермь',
    titleEn: 'Art Perm',
    cityRu: 'Пермь',
    cityEn: 'Perm',
    year: 2017,
    tags: ['выставка', 'живопись', 'картины'],
    descriptionRu: 'Подготовка и участие в фестивале Арт Пермь — написание картин для выставки.',
    descriptionEn: 'Paintings prepared for the Art Perm festival exhibition.',
  },
  'russkoe-kartonnoe-2023': {
    titleRu: 'Русское картонное',
    titleEn: 'Russian Cardboard',
    cityRu: 'Екатеринбург',
    cityEn: 'Yekaterinburg',
    year: 2023,
    tags: ['выставка', 'живопись', 'картины'],
    descriptionRu: 'Выставочный проект «Русское картонное».',
    descriptionEn: 'Exhibition project “Russian Cardboard”.',
  },
  'muzei-pri-zavode-2018': {
    titleRu: 'Музей при заводе',
    titleEn: 'Factory Museum',
    cityRu: 'Россия',
    cityEn: 'Russia',
    year: 2018,
    tags: ['музей', 'декоративная штукатурка', 'роспись'],
    descriptionRu: 'Работы для музейного пространства при заводе.',
    descriptionEn: 'Works for a factory museum space.',
  },
  paintings: {
    titleRu: 'Авторская живопись',
    titleEn: 'Original Paintings',
    cityRu: '',
    cityEn: '',
    year: 2015,
    tags: ['картины', 'живопись', 'выставка'],
    descriptionRu:
      'Авторские картины и живописные работы — от подготовки к выставкам до частных коллекций.',
    descriptionEn:
      'Original paintings — from exhibition preparation to private collections.',
  },
}

/** Виртуальные проекты из резюме без отдельной папки (для поиска/резюме) */
export const VIRTUAL_PROJECTS = [
  {
    slug: 'donna-olivia-2017',
    category: 'Общепит',
    year: 2017,
    titleRu: 'Ресторан «Donna Olivia»',
    titleEn: 'Donna Olivia Restaurant',
    cityRu: 'Екатеринбург',
    cityEn: 'Yekaterinburg',
    website: 'https://donnaolivia.ru',
    tags: ['общепит', 'декоративная штукатурка', 'художественная роспись', 'ресторан'],
    descriptionRu:
      'Нанесение декоративной штукатурки и художественная роспись в ресторане Donna Olivia.',
    descriptionEn: 'Decorative plaster and murals at Donna Olivia restaurant.',
  },
  {
    slug: 'fitnes-klub-reforma-2018',
    category: 'Клубы',
    year: 2018,
    titleRu: 'Фитнес-клуб «Реформа»',
    titleEn: 'Reforma Fitness Club',
    cityRu: 'Екатеринбург',
    cityEn: 'Yekaterinburg',
    tags: ['клуб', 'декоративная штукатурка', 'художественная роспись', 'фитнес'],
    descriptionRu:
      'Декоративная штукатурка и художественная роспись в фитнес-клубе «Реформа».',
    descriptionEn: 'Decorative plaster and murals for Reforma fitness club.',
  },
  {
    slug: 'set-kafe-a-ty-gde-2018',
    category: 'Общепит',
    year: 2018,
    titleRu: 'Сеть кафе «А ты где?»',
    titleEn: '“Where Are You?” Café Chain',
    cityRu: 'Екатеринбург',
    cityEn: 'Yekaterinburg',
    tags: ['общепит', 'декоративная штукатурка', 'художественная роспись', 'кафе'],
    descriptionRu:
      'Декоративная штукатурка и художественная роспись для сети кафе «А ты где?».',
    descriptionEn: 'Decorative plaster and murals for the “Where Are You?” café chain.',
  },
  {
    slug: 'shalet-berezka-2019',
    category: 'Общепит',
    year: 2019,
    titleRu: 'Ресторан «Шале Берёзка»',
    titleEn: 'Chalet Birch Restaurant',
    cityRu: 'Дубай',
    cityEn: 'Dubai',
    tags: ['общепит', 'декоративная штукатурка', 'художественная роспись', 'ресторан', 'дубай'],
    descriptionRu:
      'Декоративная штукатурка и художественная роспись в ресторане «Шале Берёзка», Дубай.',
    descriptionEn: 'Decorative plaster and murals for Chalet Birch restaurant in Dubai.',
  },
  {
    slug: 'restoran-osh-2019',
    category: 'Общепит',
    year: 2019,
    titleRu: 'Ресторан «Ош»',
    titleEn: 'Osh Restaurant',
    cityRu: 'Дубай',
    cityEn: 'Dubai',
    tags: ['общепит', 'декоративная штукатурка', 'художественная роспись', 'ресторан', 'дубай'],
    descriptionRu: 'Декоративная штукатурка и роспись в ресторане «Ош», Дубай.',
    descriptionEn: 'Decorative plaster and murals for Osh restaurant in Dubai.',
  },
  {
    slug: 'plov-prodzhekt-2019',
    category: 'Общепит',
    year: 2019,
    titleRu: 'Ресторан «Плов Проджект»',
    titleEn: 'Plov Project Restaurant',
    cityRu: 'Екатеринбург',
    cityEn: 'Yekaterinburg',
    tags: ['общепит', 'декоративная штукатурка', 'художественная роспись', 'ресторан'],
    descriptionRu: 'Декоративная штукатурка и роспись в ресторане «Плов Проджект».',
    descriptionEn: 'Decorative plaster and murals for Plov Project restaurant.',
  },
  {
    slug: 'more-myasa-2019',
    category: 'Общепит',
    year: 2019,
    titleRu: 'Ресторан «Море мяса»',
    titleEn: 'Sea of Meat Restaurant',
    cityRu: 'Екатеринбург',
    cityEn: 'Yekaterinburg',
    tags: ['общепит', 'художественная роспись', 'ресторан'],
    descriptionRu: 'Художественная роспись в ресторане «Море мяса».',
    descriptionEn: 'Mural work for Sea of Meat restaurant.',
  },
  {
    slug: 'kvartira-alapaevsk-2025',
    category: 'Квартиры',
    year: 2025,
    titleRu: 'Квартира — Алапаевск',
    titleEn: 'Apartment — Alapaevsk',
    cityRu: 'Алапаевск',
    cityEn: 'Alapaevsk',
    tags: ['квартира', 'декоративная штукатурка', 'лестничный проём', 'интерьер'],
    descriptionRu: 'Декоративная штукатурка лестничного проёма в квартире.',
    descriptionEn: 'Decorative plaster for a stairwell in an apartment.',
  },
]

export const RESUME = {
  aboutRu:
    'Художник-декоратор с художественным образованием и опытом работы с 2015 года. Специализируюсь на нанесении декоративной штукатурки (венецианская, травертин, микроцемент, тонкослойные и фактурные покрытия) и художественной росписи. Работаю с объектами различного масштаба: рестораны и кафе, коммерческие пространства, коттеджи, квартиры, входные группы и подъезды. С 2020 года активно работаю с жилыми и частными интерьерами — от отдельных зон до отделки «под ключ». Реализованы проекты в Екатеринбурге, Перми, Сочи, а также в Дубае.',
  aboutEn:
    'Decorative artist with a fine-arts education and professional experience since 2015. I specialize in decorative plaster (Venetian, travertine, microcement, thin-layer and textured finishes) and mural painting. I work across scales: restaurants and cafés, commercial spaces, cottages, apartments, entrances and residential lobbies. Since 2020 I have been actively working on residential and private interiors — from individual zones to turnkey finishes. Projects completed in Yekaterinburg, Perm, Sochi, and Dubai.',
  roleRu: 'Художник-декоратор',
  roleEn: 'Decorative artist',
  education: [
    {
      ru: 'Художественное училище ПУ 28, г. Березники — художник ДПИ, выпуск 2006',
      en: 'Art College PU 28, Berezniki — Decorative Applied Arts, 2006',
    },
    {
      ru: 'Пермский государственный институт культуры, кафедра живописи — художник, выпуск 2015',
      en: 'Perm State Institute of Culture, Painting Department — Artist, 2015',
    },
  ],
  career: [
    {
      years: '2015–2016',
      ru: 'Пермский театр «У Моста» — художник-декоратор / монтировщик сцен',
      en: 'Perm Theatre “At the Bridge” — scenic artist / stage installer',
    },
    {
      years: '2016–2017',
      ru: 'Подготовка и участие в фестивале Арт Пермь',
      en: 'Preparation and participation in Art Perm festival',
    },
  ],
}
